FROM php:7.2

# ARG DEBIAN_FRONTEND=noninteractive

#------------------ INSTALL ------------------#

# DEBIAN
# RUN apt-get update -y
# RUN apt-get upgrade -y
# RUN apt-get install -y sudo \
# 					   dialog \
# 					   apt-utils \
# 					   wget \
# 					   apt-utils

#------------------ CONFIGURATION ------------------#

# PHP 7
# COPY ./php.ini /tmp/
# RUN cat /tmp/php.ini >> /etc/php/7.0/cli/php.ini
# RUN cat /tmp/php.ini >> /etc/php/7.0/apache2/php.ini
# RUN rm -rf /tmp/php.ini